### ISSUE TITLE
Calculator does not accept float numbers as current level

### ISSUE THREAD

**Issue by abdurahim-H** [0Slaye/pcalculator#1]
The calculator for experience points does not currently support floating-point numbers as valid input for the current level. This can be problematic, as users may have fractional levels (e.g., 3.76) based on partial progress, but the calculator only accepts integers.

Steps to Reproduce:
1. Open the calculator.
2. Enter a floating-point number (e.g., 3.76) as the current level.
3. The calculator returns an error stating that the input is not valid.

Suggestion for Fix:
In the function that handles user input, it would be better to convert the input to a float instead of an int to support decimal values. For example, changing the input parsing logic like this:

```
def sinput(value: str):
    try:
        result = float(input(f"{value}: "))
    except ValueError:
        return -1
    return result
```

This should allow users to input their level with decimals, fixing the issue

**Comment by slqye** [comment]
Hi, thanks you!
I missed that when i was rewriting the code in python. This should be fixed now.
Have a great day!
